[package]
name = "proxy-deployer-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dharitri <contact@dharitri.com>"]

[dev-dependencies]

[dependencies.proxy-deployer]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.6"
default-features = false
