[package]
name = "lkmex-transfer-wasm"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
crate-type = [ "cdylib",]

[workspace]
members = [ ".",]

[dev-dependencies]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"

[dependencies.lkmex-transfer]
default-features = false
path = ".."

[dependencies.dharitri-wasm-node]
version = "=0.10.6"

[dependencies.dharitri-wasm-output]
version = "=0.10.6"
features = ["wasm-output-mode"]
