[package]
name = "farm-staking-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.farm-staking]
path = ".."

[dependencies.dharitri-wasm]
version = "=0.10.6"

[dependencies.dharitri-wasm-debug]
version = "=0.10.6"
