[package]
name = "lkmex-transfer-abi"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.lkmex-transfer]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.6"
default-features = false
