[package]
name = "farm-with-locked-rewards-meta"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.farm-with-locked-rewards]
path = ".."

[dependencies.dharitri-wasm]
version = "=0.10.6"

[dependencies.dharitri-wasm-debug]
version = "=0.10.6"
