[package]
name = "pair-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.pair]
path = ".."

[dependencies.dharitri-wasm]
version = "=0.10.6"
features = ["dct-token-payment-legacy-decode",]

[dependencies.dharitri-wasm-debug]
version = "=0.10.6"

