[package]
name = "fuzz"
version = "0.0.0"
authors = [ "sorin-petreasca <sorin.petreasca@dharitri.com>",]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.dharitri-wasm]
version = "=0.10.6"
features = ["dct-token-payment-legacy-decode",]

[dependencies.dharitri-wasm-debug]
version = "=0.10.6"

[dependencies.pausable]
path = "../../common/modules/pausable"

[dependencies.config]
path = "../../common/modules/farm/config"

[dependencies.farm_token]
path = "../../common/modules/farm/farm_token"

[dependencies.rewards]
path = "../../common/modules/farm/rewards"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.farm-staking]
path = "../../farm-staking/farm-staking"

[dependencies.factory]
path = "../../locked-asset/factory"

[dependencies.pair-mock]
path = "../pair-mock"

[dependencies.price-discovery]
path = "../price-discovery"

[dependencies.simple-lock]
path = "../../locked-asset/simple-lock"

[dependencies.farm]
path = "../farm"

[dependencies.pair]
path = "../pair"

[dependencies.router]
path = "../router"

[dependencies]
num-bigint = "0.4.2"
rand = "0.8.4"
