[package]
name = "events"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@dharitri.com>",]
edition = "2018"

[lib]
path = "src/events.rs"

[dependencies.common_structs]
path = "../../../common_structs"

[dependencies.contexts]
path = "../contexts"

[dependencies.dharitri-wasm]
version = "=0.10.6"
features = ["dct-token-payment-legacy-decode",]
