[package]
name = "governance-v2-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dharitri <contact@dharitri.com>"]

[dev-dependencies]

[dependencies.governance-v2]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.6"
default-features = false
