[package]
name = "proxy_dex-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.proxy_dex]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.6"
default-features = false
