[package]
name = "fees-collector-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.fees-collector]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "=0.10.6"
