[package]
name = "fees-collector-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dharitri <contact@dharitri.com>"]

[dev-dependencies]

[dependencies.fees-collector]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.6"
default-features = false
