[package]
name = "factory-abi"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.factory]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.4"
default-features = false
