[package]
name = "price-discovery-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dorin Iancu <dorin.iancu@dharitri.com>"]

[dependencies.price-discovery]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.6"
default-features = false
