[package]
name = "price-discovery-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Dorin Iancu <dorin.iancu@dharitri.com>" ]

[dependencies.price-discovery]
path = ".."

[dependencies.dharitri-wasm]
version = "=0.10.6"

[dependencies.dharitri-wasm-debug]
version = "=0.10.6"
